"""add telegram_user_id to students

Revision ID: ef3732184a52
Revises: 
Create Date: 2026-09-06 00:54:58.135506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef3732184a52'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('telegram_username', sa.String(length=128), nullable=True))
    op.add_column('students', sa.Column('telegram_user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'students', ['telegram_username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_column('students', 'telegram_user_id')
    op.drop_column('students', 'telegram_username')
    # ### end Alembic commands ###
