"""add telegram_user_id to students

Revision ID: ef3732184a52
Revises: 
Create Date: 2026-09-06 00:54:58.135506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Column


# revision identifiers, used by Alembic.
revision: str = 'ef3732184a52'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(Column('telegram_username', sa.String(length=128), nullable=True))
        batch_op.add_column(Column('telegram_user_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_students_telegram_username'), ['telegram_username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_students_telegram_username'), type_='unique')
        batch_op.drop_column('telegram_user_id')
        batch_op.drop_column('telegram_username')
    # ### end Alembic commands ###
